# Generated by Django 6.0.3 on 2026-06-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_private_key_user_public_key_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
