# Generated by Django 6.0.3 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_notification_type_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_work', 'Nueva obra publicada'), ('new_follower', 'Nuevo suscriptor / seguidor'), ('new_saved_work', 'Nueva obra guardada')], default='new_work', max_length=30),
        ),
    ]
