# Generated by Django 6.0.3 on 2026-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_work', 'Nueva obra publicada'), ('new_follower', 'Nuevo suscriptor / seguidor'), ('new_saved_work', 'Nueva obra guardada'), ('approved_work', 'Obra aprobada por el administrador'), ('rejected_work', 'Obra rechazada por el administrador')], default='new_work', max_length=30),
        ),
    ]
