# Generated by Django 6.0.3 on 2026-09-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
    ]
