# Generated by Django 6.0.3 on 2026-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_private_key_remove_user_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_work', 'Nueva obra publicada'), ('new_follower', 'Nuevo suscriptor / seguidor'), ('new_saved_work', 'Nueva obra guardada'), ('approved_work', 'Obra aprobada por el administrador'), ('rejected_work', 'Obra rechazada por el administrador'), ('plan_expiring', 'Plan a punto de expirar')], default='new_work', max_length=30),
        ),
    ]
