# Generated by Django 6.0.3 on 2026-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_notification_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('author', 'Autor'), ('consumer', 'Consumidor')], default='consumer', max_length=10, verbose_name='Rol'),
        ),
    ]
