# Generated by Django 6.0.3 on 2026-10-09 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_role'),
        ('works', '0018_alter_book_isbn_alter_paint_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_work', 'Nueva obra publicada'), ('new_follower', 'Nuevo suscriptor / seguidor'), ('new_saved_work', 'Nueva obra guardada'), ('approved_work', 'Obra aprobada por el administrador'), ('rejected_work', 'Obra rechazada por el administrador'), ('plan_expiring', 'Plan a punto de expirar')], default='new_work', max_length=30, verbose_name='Tipo de notificación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='works.work', verbose_name='Obra'),
        ),
    ]
