# Generated by Django 5.2.10 on 2026-02-22 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('validate_work', 'Can validate or reject works'), ('generate_hash', 'Can generate authorship hash'), ('view_all_works', 'Can view all works')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
                ('pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
                ('duration', models.FloatField()),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('type', models.CharField(choices=[('oil', 'Oil'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('digital', 'Digital')], max_length=20)),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('type', models.CharField(choices=[('marble', 'Marble'), ('bronze', 'Bronze'), ('wood', 'Wood'), ('clay', 'Clay')], max_length=20)),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
                ('programming_language', models.CharField(max_length=50)),
                ('repository_url', models.URLField(blank=True, null=True)),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
                ('duration', models.FloatField()),
            ],
            bases=('works.work',),
        ),
    ]
