# Generated by Django 6.0.3 on 2026-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='binary_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
