# Generated by Django 6.0.3 on 2026-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_binary_file_work_file_name_work_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('book', 'Libro'), ('music', 'Música'), ('video', 'Vídeo'), ('software', 'Software'), ('paint', 'Pintura'), ('sculpture', 'Escultura')], default='book', max_length=20),
        ),
    ]
