# Generated by Django 6.0.3 on 2026-04-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_work_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='license',
            field=models.CharField(choices=[('by', 'BY'), ('by-sa', 'BY-SA'), ('by-nd', 'BY-ND'), ('by-nc', 'BY-NC'), ('by-nc-sa', 'BY-NC-SA'), ('by-nc-nd', 'BY-NC-ND')], default='by', max_length=20),
        ),
    ]
