# Generated by Django 6.0.3 on 2026-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='license',
            field=models.CharField(choices=[('none', 'Sin licencia'), ('by', 'BY'), ('by-sa', 'BY-SA'), ('by-nd', 'BY-ND'), ('by-nc', 'BY-NC'), ('by-nc-sa', 'BY-NC-SA'), ('by-nc-nd', 'BY-NC-ND')], default='by', max_length=20),
        ),
    ]
