# Generated by Django 6.0.3 on 2026-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_work_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='type',
            field=models.CharField(choices=[('oil', 'Óleo'), ('acrylic', 'Acrílico'), ('watercolor', 'Acuarela'), ('digital', 'Digital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='type',
            field=models.CharField(choices=[('marble', 'Marmol'), ('bronze', 'Bronce'), ('wood', 'Madera'), ('clay', 'Arcilla')], max_length=20),
        ),
    ]
