# Generated by Django 6.0.3 on 2026-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_alter_paint_type_alter_sculpture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='type',
            field=models.CharField(choices=[('marble', 'Mármol'), ('bronze', 'Bronce'), ('wood', 'Madera'), ('clay', 'Arcilla')], max_length=20),
        ),
    ]
