# Generated by Django 6.0.3 on 2026-05-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('works', '0007_alter_sculpture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='plan_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='subscriptions.subscriptionplan'),
        ),
    ]
