# Generated by Django 6.0.3 on 2026-05-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_work_plan_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='hash_security',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
