# Generated by Django 6.0.3 on 2026-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_work_hash_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='software',
            name='documentation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='resume_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='resume_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='resume_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
