# Generated by Django 6.0.3 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_book_genre_book_language_music_album_music_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='license',
            field=models.CharField(choices=[('by', 'BY'), ('by-sa', 'BY-SA'), ('by-nd', 'BY-ND'), ('by-nc', 'BY-NC'), ('by-nc-sa', 'BY-NC-SA'), ('by-nc-nd', 'BY-NC-ND')], default='by', max_length=20),
        ),
    ]
