# Generated by Django 6.0.3 on 2026-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_alter_work_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='file_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='work',
            name='hash_security',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='license',
            field=models.CharField(choices=[('by', 'BY'), ('by-sa', 'BY-SA'), ('by-nd', 'BY-ND'), ('by-nc', 'BY-NC'), ('by-nc-sa', 'BY-NC-SA'), ('by-nc-nd', 'BY-NC-ND')], default='by', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
