# Generated by Django 6.0.3 on 2026-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_alter_book_isbn_alter_work_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo (IA o Manual)'),
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprobada'), ('appealed', 'Revisión manual solicitada'), ('rejected_manual', 'Rechazada definitivamente'), ('published', 'Publicada')], default='pending_ai', max_length=20, verbose_name='Estado de validación'),
        ),
    ]
