# Generated by Django 6.0.3 on 2026-10-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_authorsubscription_options_and_more'),
        ('works', '0013_work_rejection_reason_work_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Música', 'verbose_name_plural': 'Música'},
        ),
        migrations.AlterModelOptions(
            name='paint',
            options={'verbose_name': 'Pintura', 'verbose_name_plural': 'Pinturas'},
        ),
        migrations.AlterModelOptions(
            name='sculpture',
            options={'verbose_name': 'Escultura', 'verbose_name_plural': 'Esculturas'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': [('validate_work', 'Can validate or reject works'), ('generate_hash', 'Can generate authorship hash'), ('view_all_works', 'Can view all works')], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lenguaje'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name='Páginas'),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(blank=True, max_length=200, verbose_name='Álbum'),
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.FloatField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='height',
            field=models.FloatField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='type',
            field=models.CharField(choices=[('oil', 'Óleo'), ('acrylic', 'Acrílico'), ('watercolor', 'Acuarela'), ('digital', 'Digital')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='weight',
            field=models.FloatField(verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='height',
            field=models.FloatField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='type',
            field=models.CharField(choices=[('marble', 'Mármol'), ('bronze', 'Bronce'), ('wood', 'Madera'), ('clay', 'Arcilla')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='weight',
            field=models.FloatField(verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='software',
            name='documentation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url repositorio de la documentación'),
        ),
        migrations.AlterField(
            model_name='software',
            name='programming_language',
            field=models.CharField(max_length=50, verbose_name='Lenguaje de programación'),
        ),
        migrations.AlterField(
            model_name='software',
            name='repository_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url repositorio del proyecto'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='work',
            name='binary_file',
            field=models.BinaryField(blank=True, null=True, verbose_name='Obra original'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creando el'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre fichero obra original'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tipo fichero obra original'),
        ),
        migrations.AlterField(
            model_name='work',
            name='hash_security',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Hash de la obra'),
        ),
        migrations.AlterField(
            model_name='work',
            name='license',
            field=models.CharField(choices=[('by', 'BY'), ('by-sa', 'BY-SA'), ('by-nd', 'BY-ND'), ('by-nc', 'BY-NC'), ('by-nc-sa', 'BY-NC-SA'), ('by-nc-nd', 'BY-NC-ND')], default='by', max_length=50, verbose_name='Licencia'),
        ),
        migrations.AlterField(
            model_name='work',
            name='plan_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='subscriptions.subscriptionplan', verbose_name='Plan mínimo requerido'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume_file',
            field=models.BinaryField(blank=True, null=True, verbose_name='Muestra gratuita'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre fichero muestra gratuita'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tipo fichero muestra gratuita'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('book', 'Libro'), ('music', 'Música'), ('video', 'Vídeo'), ('software', 'Software'), ('paint', 'Pintura'), ('sculpture', 'Escultura')], default='book', max_length=20, verbose_name='Tipo de obra'),
        ),
    ]
