# Generated by Django 6.0.3 on 2026-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_alter_book_options_alter_music_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Lenguaje'),
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.FloatField(verbose_name='Duración (min)'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='height',
            field=models.FloatField(verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='weight',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='height',
            field=models.FloatField(verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='weight',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(verbose_name='Duración (min)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
