# Generated by Django 6.0.3 on 2026-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_alter_book_genre_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Idioma'),
        ),
    ]
