# Generated by Django 6.0.3 on 2026-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Narrativa / Ficción'), ('mystery', 'Misterio / Suspense'), ('scifi_fantasy', 'Ciencia Ficción / Fantasía'), ('romance', 'Novela Romántica'), ('historical', 'Novela Histórica'), ('poetry', 'Poesía'), ('theater', 'Teatro'), ('essay', 'Ensayo'), ('biography', 'Biografía'), ('science', 'Divulgación Científica'), ('self_help', 'Desarrollo Personal'), ('children', 'Infantil / Juvenil'), ('comic', 'Cómic'), ('other', 'Otro')], max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('other', 'Otro')], max_length=100, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('urban', 'Urbano / Reggaetón / Trap'), ('electronic', 'Electrónica / Dance / Lo-Fi'), ('hiphop', 'Hip Hop / Rap'), ('indie', 'Indie / Cantautor'), ('classical', 'Clásica / Instrumental'), ('jazz', 'Jazz'), ('folk', 'Folk / Tradicional / Flamenco'), ('other', 'Otro')], max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Ficción'), ('documentary', 'Documental'), ('videoclip', 'Videoclip'), ('animation', 'Animación'), ('tutorial', 'Tutorial'), ('short_film', 'Cortometraje'), ('talk_podcast', 'Entrevista / Charlas / Podcast'), ('advertising', 'Publicitario'), ('theater_dance', 'Teatro / Danza'), ('other', 'Otro')], max_length=100, verbose_name='Género'),
        ),
    ]
