# Generated by Django 6.0.3 on 2026-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_alter_book_genre_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
    ]
