# Generated by Django 6.0.3 on 2026-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_setup_groups_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho (cm)'),
        ),
    ]
