# Generated by Django 6.0.3 on 2026-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_userwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_download_originals',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features_raw',
            field=models.TextField(blank=True, default='', help_text='Introduce las características separadas por comas.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='points',
            field=models.IntegerField(default=15),
        ),
    ]
