# Generated by Django 6.0.3 on 2026-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_savework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features_raw',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='points',
            field=models.IntegerField(default=15, editable=False),
        ),
    ]
