# Generated by Django 6.0.3 on 2026-10-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_subscriptionplan_features_raw_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsubscription',
            options={'verbose_name': 'Suscripción a autor', 'verbose_name_plural': 'Suscripciones a autores'},
        ),
        migrations.AlterModelOptions(
            name='savework',
            options={'verbose_name': 'Obra guardada', 'verbose_name_plural': 'Obras guardadas'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Plan de suscripción', 'verbose_name_plural': 'Planes de suscripción'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Suscripción de usuario', 'verbose_name_plural': 'Suscripciones de usuario'},
        ),
        migrations.AlterModelOptions(
            name='userwallet',
            options={'verbose_name': 'Cartera de puntos', 'verbose_name_plural': 'Carteras de puntos'},
        ),
        migrations.AlterUniqueTogether(
            name='authorsubscription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savework',
            unique_together=set(),
        ),
    ]
