# Generated by Django 6.0.3 on 2026-10-09 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_authorsubscription_options_and_more'),
        ('works', '0018_alter_book_isbn_alter_paint_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsubscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='authorsubscription',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Consumidor'),
        ),
        migrations.AlterField(
            model_name='authorsubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='savework',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_works', to=settings.AUTH_USER_MODEL, verbose_name='Consumidor'),
        ),
        migrations.AlterField(
            model_name='savework',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='savework',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='works.work', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='points',
            field=models.IntegerField(default=15, editable=False, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
